# Generated by Django 5.2.17 on 2026-10-02 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="Integer minor units (cents).")),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("payment_token", models.CharField(max_length=64)),
                ("method", models.CharField(blank=True, max_length=8)),
                ("last4", models.CharField(blank=True, max_length=4)),
                ("brand_or_bank_type", models.CharField(blank=True, max_length=32)),
                (
                    "processor_reference",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card_declined", "Card Declined"),
                            ("insufficient_funds", "Insufficient Funds"),
                            ("processor_error", "Processor Error"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_keys",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("processor_reference", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=16)),
                ("failure_code", models.CharField(blank=True, max_length=32, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                            ("ignored_stale", "Ignored Stale"),
                            ("ignored_redundant", "Ignored Redundant"),
                            ("conflict", "Conflict"),
                        ],
                        max_length=32,
                    ),
                ),
                ("delivery_count", models.PositiveIntegerField(default=1)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("received_at",),
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="1-based position within the payment."),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment_created", "Payment Created"),
                            ("processor_webhook", "Processor Webhook"),
                            ("processor_unavailable", "Processor Unavailable"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card_declined", "Card Declined"),
                            ("insufficient_funds", "Insufficient Funds"),
                            ("processor_error", "Processor Error"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "amount_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Signed cents this entry moves (captures are positive; refunds would be negative).",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(help_text="When the processor says it happened."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="payments.payment",
                    ),
                ),
                (
                    "webhook_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entry",
                        to="payments.webhookevent",
                    ),
                ),
            ],
            options={
                "ordering": ("payment_id", "sequence"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "sequence"), name="ledger_sequence_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("to_status__in", ["succeeded", "failed"])),
                        fields=("payment",),
                        name="ledger_one_terminal_entry_per_payment",
                    ),
                ],
            },
        ),
    ]
