# Generated by Django 5.2.17 on 2026-10-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessorToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("method", models.CharField(max_length=8)),
                ("last4", models.CharField(max_length=4)),
                ("brand_or_bank_type", models.CharField(max_length=32)),
                ("final_status", models.CharField(max_length=16)),
                ("failure_code", models.CharField(blank=True, max_length=32, null=True)),
                ("settle_after_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessorCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("processor_reference", models.CharField(max_length=64, unique=True)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("final_status", models.CharField(max_length=16)),
                ("failure_code", models.CharField(blank=True, max_length=32, null=True)),
                ("settle_after_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="mock_processor.processortoken",
                    ),
                ),
            ],
        ),
    ]
